// <auto-generated />
using System;
using FraudPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FraudPortal.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221211070406_need-to-action-edit")]
    partial class needtoactionedit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FraudPortal.Data.Fraud_Fact_Portal", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Amount_Success")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Amount_unSuccess")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankBin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountOfRepeat")
                        .HasColumnType("int");

                    b.Property<int?>("CountOfSourcePan")
                        .HasColumnType("int");

                    b.Property<int?>("CountOfTerminal")
                        .HasColumnType("int");

                    b.Property<int?>("CountOfTransaction_Success")
                        .HasColumnType("int");

                    b.Property<int?>("CountOfTransaction_unSuccess")
                        .HasColumnType("int");

                    b.Property<long?>("Date_id")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("DestinationSECPAN")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Detail1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Detail2")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Detail3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Detail4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiffTime1")
                        .HasColumnType("int");

                    b.Property<int?>("DiffTime2")
                        .HasColumnType("int");

                    b.Property<string>("EncryptDestinationPAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuildTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedToAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("No");

                    b.Property<decimal?>("P_SorcePan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("P_Unsucsess")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("Period")
                        .HasColumnType("bigint");

                    b.Property<string>("PosConnectionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrCode_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Risk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rull_id")
                        .HasColumnType("int");

                    b.Property<string>("SourcePan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Terminal")
                        .HasColumnType("bigint");

                    b.Property<string>("TypePeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("User_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("editdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("id");

                    b.ToTable("fraud_Fact_Portal");
                });

            modelBuilder.Entity("FraudPortal.Data.IdentifyDailyFrauds_RuleList", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RuleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WeightRule")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("condition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuleID");

                    b.ToTable("IdentifyDailyFrauds_RuleList");
                });

            modelBuilder.Entity("FraudPortal.Data.UserInGroup", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkGroupId")
                        .HasColumnType("int");

                    b.Property<string>("WorkGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserName");

                    b.HasIndex("WorkGroupId");

                    b.ToTable("UserInGroups");
                });

            modelBuilder.Entity("FraudPortal.Data.WorkGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkGroups");
                });

            modelBuilder.Entity("FraudPortal.Data.UserInGroup", b =>
                {
                    b.HasOne("FraudPortal.Data.WorkGroup", "WorkGroup")
                        .WithMany("userInGroups")
                        .HasForeignKey("WorkGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("FraudPortal.Data.WorkGroup", b =>
                {
                    b.Navigation("userInGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
